### ISSUE TITLE
Blog offline

### ISSUE THREAD

**Issue by SANCLA** [tomascrespo/ESP8266-soil-sensor#1]
Just a heads-up: your website/blog appears to be offline. 
My heart skipped a beat because I recently ordered parts to build a couple of these sensors. And when I finally got started, your site was down. Fortunately, I found your GitHub repo!

Hope everything is okay, and thanks for sharing your project!

**Comment by tomascrespo** [comment]
Ups! Server hard disk full! 😅

I will solve trough the day

Abu question, ask

**Comment by tomascrespo** [comment]
Solved! Blog online again

**Comment by tomascrespo** [comment]
Blog online again
